# Build stage
FROM python:3.12-slim as builder

WORKDIR /app

COPY app.py ./
RUN pip install flask

# Runtime stage
FROM python:3.12-slim

WORKDIR /app
COPY --from=builder /app /app

#EXPOSE 5000
CMD ["python", "app.py"]
